### ISSUE TITLE
tpl-entries failed in version 1.0.0

### ISSUE THREAD

**Issue by shenfan19** [pajoma/vscode-journal#125]
In recent days, I found my daily note template written in tpl-entry didn't work. It always kept the origional struct however I change the content.
After I rolled back to the version 0.11.2, it works again.
I guess there's a bug in the recent update.

Btw, I have used the plugin for 1 year, it's very good, thanks!

**Comment by dallanlee** [comment]
I've been dealing with this issue as well and didn't think to try rolling back …I was disabling other extensions I recently installed 🙃 rolling back fixes the issue

I agree this is excellent plugin and I've only just started using it a few weeks ago - thanks!

**Comment by pajoma** [comment]
Thanks, I will look into it.

**Comment by pajoma** [comment]
Ok, the bug seems to be related to #72, 

The tpl-entry setting is deprecated, supporting the old values would be too complex to solve now. 

I have updated the [settings description](https://github.com/pajoma/vscode-journal/blob/125-entry-template/docs/settings.md) and reworked the deprecation markers for settings.
