### ISSUE TITLE
Declaring a new "journal.base" has no effect

### ISSUE THREAD

**Issue by llamicron** [pajoma/vscode-journal#17]
After installing, notes are stored in `~/Journal` by default. I put the following line in my vscode user settings:
```
"journal.base": "/Users/llamicron/.journal"
```
and notes are still stored in `~/Journal`. There's no syntax error in my `settings.json`. Am i doing something wrong or is there a bug here?

**Comment by pajoma** [comment]
Hmm, strange. I changed my path from 
`"journal.base": "[some special path]",` 
to
`"journal.base": "",` 
and restarted. New file was created in 
`C:/Users/pajoma/Journal/2017/06/10.md` (yes, Windows here currently)
Next changing it to
`C:/Users/pajoma/.journal` (as in your example)
and after restart of vscode the new file was created in the correct location. 

I can't really reproduce the error, since I have no Mac available.

**Comment by llamicron** [comment]
I think I found my problem. When I installed the package, I changed the path and ran VSCode's reload command. After completely closing VSCode and re-opening it, the new path seems to have taken effect. Maybe it requires a full restart instead of a reload. MacOS usually doesn't fully close application when they are "closed", so perhaps I needed to completely restart. Thanks, and sorry for the inconvenience.
