### ISSUE TITLE
Titel of document contains additional whitespace

### ISSUE THREAD

**Issue by kaiwood** [pajoma/vscode-journal#2]
When a new document gets created, the title contains one trailing space, see attached screenshot. (the red color if from another extension that shows whitespace, just in case you wonder)

![vscode-journal](https://cloud.githubusercontent.com/assets/7542/19981323/d1050962-a201-11e6-88b3-5fb48393c28b.gif)

Same problem for journal:note with a custom title.

**Comment by pajoma** [comment]
Thanks for the hint. You can change it yourself in the setting ´journal.tpl-page´, the default value is `# {content} \n\n` (with {content} being replaced by the date or note title string). The space before the linebreak ´\n´ is the problem here, you can just remove it, I will change it for the next version.

**Comment by kaiwood** [comment]
Ah, great, that setting works!

And by the way: Thank you so much for this extension. I had something similar for VoodooPad (https://github.com/kaiwood/voodoopad-journal) which I am no longer using and was about to write something similar for VSCode when you released this one. Saved me quite some time that you did it. Keep up the good work 👍

**Comment by pajoma** [comment]
Thanks, glad to save you some time ;)
