### ISSUE TITLE
Jump to today's entry re-adds notes and results in duplicates

### ISSUE THREAD

**Issue by AmerM137** [pajoma/vscode-journal#78]
Using the jump to today's entry command duplicates the Note links every time it's executed but not the memos.

Using this command should simply navigate to the day's entry.

**Comment by pajoma** [comment]
Yes, this is annoying.. The syncing is always triggered when an entry is opened, since I often create files outside of vscode and place them in the attachements folder. The links are then automatically created. 

I plan to switch links to more readable links using markdown similar to style using in the Markdown Notes extension
